spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/userservice_db
    username: user_service
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true