spring:
  application:
    name: USER-SERVICE

  profiles:
    active: default

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/userservice_db
    username: user_service
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  config:
    import: "optional:configserver:https://verbose-space-meme-4447pjpxqjxcpxp-8085.app.github.dev/"  

# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

#     fetch-registry: true
#     register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        minimumNumberOfCalls: 5  
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

# 👉 Imagine this:
# Service runs normally
# Out of last 10 calls, if 5 fail → ❌ OPEN
# Wait 6 seconds
# Allow 3 test calls
# If success → ✅ CLOSE
# If fail → ❌ OPEN again