spring:
  application:
    name: USER-SERVICE

  profiles:
    active: default

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/userservice_db
    username: user_service
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  config:
    import: "optional:configserver:https://verbose-space-meme-4447pjpxqjxcpxp-8085.app.github.dev/"  

# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#     fetch-registry: true
#     register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        minimumNumberOfCalls: 5  
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

# Full Circuit Breaker Flow:
# Service runs normally
# Out of last 10 calls, if 5 fail → ❌ OPEN
# Wait 6 seconds
# Allow 3 test calls
# If success → ✅ CLOSE
# If fail → ❌ OPEN again

  retry:
    instances:
      userServiceRetry:
        maxAttempts: 3  #maximum 3 times (1 original + 2 retries)
        waitDuration: 2s  #Wait 2 seconds between retries
        retryExceptions:
          - java.lang.IllegalStateException  #Retry only for allowed Exceptions
        ignoreExceptions:
          - java.lang.NullPointerException  #Don't retry for this Exceptions

# Full Retry Flow:
# Call service
# If IllegalStateException occurs → retry
# Wait 2 sec
# Retry again
# Max 3 attempts
# If still fails → final failure
# 👉 If NullPointerException → ❌ no retry, fail instantly

  rateLimiter:
    instances:
      userServiceRateLimiter:
        limitForPeriod: 5  # Max 5 calls per period
        limitRefreshPeriod: 1m  # in every 1 minute
        # timeoutDuration: 0  # No waiting, fail immediately if limit exceeded - (fail fast)
        timeoutDuration: 5s
# Full Flow Example
# Scenario (within 1 minute)
# Request 1 → ✅ allowed
# Request 2 → ✅ allowed
# Request 3 → ✅ allowed
# Request 4 → ✅ allowed
# Request 5 → ✅ allowed
# Request 6 → ❌ rejected immediately
# 👉 Because limit reached