spring:
  application:
    name: USER-SERVICE

  profiles:
    active: default

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/userservice_db
    username: user_service
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  config:
    import: "optional:configserver:https://verbose-space-meme-4447pjpxqjxcpxp-8085.app.github.dev/"  

# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

#     fetch-registry: true
#     register-with-eureka: true