server: 
  port: 8085

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShubhamSKhedekar/user-rating-microservice-config
          clone-on-start: true